stages:
  - build
  # - test
  - deploy

variables:
  SERVICE_NAME: api-gateway
  IMAGE_NAME: '$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA'

build_image:
  stage: build
  image: docker:20.10.16-dind
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$IMAGE_NAME" .
    - docker push "$IMAGE_NAME"
  only:
    - main

deploy_production:
  stage: deploy
  script:
    - ssh user@yourserver "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY && docker compose pull && docker compose up -d"
  only:
    - main
  needs:
    - build_image
